package com.StCroixRods.budget_tracker;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.time.LocalDate;
@Entity
public class Expense {
    //ID for the purchase, will be autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    //cost of the purchase
    @DecimalMin("0.01") @NotNull
    private Double amount;

    //what the purchase was
    @NotBlank
    private String description;

    //date of purchase
    @NotNull
    private LocalDate date;

    //category of purchase
    //Tag stores the category as a string in database, not number
    @Enumerated(EnumType.STRING)
    @NotNull
    private ExpenseCategory category;

    public Expense (Double amount, String description, LocalDate date, ExpenseCategory category) {
        this.amount = amount;
        this.description = description;
        this.date = date;
        this.category = category;
    }
    public Expense (Double amount, String description, LocalDate date) {
        this(amount, description, date, ExpenseCategory.OTHER);
    }
    public Expense() {
    }
    public ExpenseCategory getCategory() {return this.category;}

    public Long getId() {
        return id;
    }

    public LocalDate getDate() {
        return date;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public void setCategory(ExpenseCategory category) {
        this.category = category;
    }

    public String getDescription() {
        return description;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
